project:
  type: website
  output-dir: docs

website:
  title: "Microtutorials"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SebasSaenz
      - icon: twitter
        href: https://twitter.com/SaenzJohanS
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

